// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCdoAn5J2BHNVW4OEcUn4T0nSEVrCsCpmE',
    appId: '1:1063175917211:web:68f4317a734a6299e3003e',
    messagingSenderId: '1063175917211',
    projectId: 'criminal-catcher',
    authDomain: 'criminal-catcher.firebaseapp.com',
    storageBucket: 'criminal-catcher.firebasestorage.app',
    measurementId: 'G-W92XMHZCH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA7imVkti6_zlBf7XTDTadjINN5tY-SG8',
    appId: '1:1063175917211:android:6f5ec967d80cd6e6e3003e',
    messagingSenderId: '1063175917211',
    projectId: 'criminal-catcher',
    storageBucket: 'criminal-catcher.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzdoz2EoonmdDOrmUA5VMjf3drP4bSDAM',
    appId: '1:1063175917211:ios:dfe623545dcb027de3003e',
    messagingSenderId: '1063175917211',
    projectId: 'criminal-catcher',
    storageBucket: 'criminal-catcher.firebasestorage.app',
    iosBundleId: 'com.example.criminalCatcher',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzdoz2EoonmdDOrmUA5VMjf3drP4bSDAM',
    appId: '1:1063175917211:ios:dfe623545dcb027de3003e',
    messagingSenderId: '1063175917211',
    projectId: 'criminal-catcher',
    storageBucket: 'criminal-catcher.firebasestorage.app',
    iosBundleId: 'com.example.criminalCatcher',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCdoAn5J2BHNVW4OEcUn4T0nSEVrCsCpmE',
    appId: '1:1063175917211:web:18706829c9a15438e3003e',
    messagingSenderId: '1063175917211',
    projectId: 'criminal-catcher',
    authDomain: 'criminal-catcher.firebaseapp.com',
    storageBucket: 'criminal-catcher.firebasestorage.app',
    measurementId: 'G-5F0LQ7YEP9',
  );
}
